import { ThemeToggle } from "components/ToggleTheme";
import { ThemeProvider } from "components/theme-provider";
import { Button } from "components/ui/button";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import { Navigation } from "./components/NavigationList";
import SessionProvider from "./components/SessionProvider";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "simlpe rfc demo",
	description: "Generated by create next app",
};
export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession();

	return (
		<html lang='en'>
			<body className={inter.className}>
				<SessionProvider session={session}>
					<ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
						<div className="flex justify-around items-center p-2">
							<ThemeToggle />
							<Button variant={"outline"}>
								{" "}
								<Link href='/react-patterns'> See React patterns </Link>
							</Button>
						</div>
						<Navigation />
						{children}
					</ThemeProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
