import { ThemeProvider } from "components/theme-provider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import SessionProvider from "./components/SessionProvider";
import "./globals.css";
import { Navigation } from "./components/NavigationList";
import { ThemeToggle } from "components/ToggleTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "simlpe rfc demo",
	description: "Generated by create next app",
};
export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession();

	return (
		<html lang='en'>
			<body className={inter.className}>
				<SessionProvider session={session}>
					<ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
						<ThemeToggle />
						<Navigation />
						{children}
					</ThemeProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
